// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/predicate"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/pkg/auth"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// Age applies equality check predicate on the "age" field. It's identical to AgeEQ.
func Age(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAge, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNickname, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldScore, v))
}

// IsVerified applies equality check predicate on the "is_verified" field. It's identical to IsVerifiedEQ.
func IsVerified(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsVerified, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// TestUUID applies equality check predicate on the "test_uuid" field. It's identical to TestUUIDEQ.
func TestUUID(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTestUUID, v))
}

// TestNillableUUID applies equality check predicate on the "test_nillable_uuid" field. It's identical to TestNillableUUIDEQ.
func TestNillableUUID(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTestNillableUUID, v))
}

// RemoteToken applies equality check predicate on the "remote_token" field. It's identical to RemoteTokenEQ.
func RemoteToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRemoteToken, v))
}

// TestTime applies equality check predicate on the "test_time" field. It's identical to TestTimeEQ.
func TestTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTestTime, v))
}

// LastLoginIP applies equality check predicate on the "last_login_ip" field. It's identical to LastLoginIPEQ.
func LastLoginIP(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLoginIP, v))
}

// VerificationCode applies equality check predicate on the "verification_code" field. It's identical to VerificationCodeEQ.
func VerificationCode(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerificationCode, v))
}

// InternalID applies equality check predicate on the "internal_id" field. It's identical to InternalIDEQ.
func InternalID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldInternalID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// AgeEQ applies the EQ predicate on the "age" field.
func AgeEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAge, v))
}

// AgeNEQ applies the NEQ predicate on the "age" field.
func AgeNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAge, v))
}

// AgeIn applies the In predicate on the "age" field.
func AgeIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldAge, vs...))
}

// AgeNotIn applies the NotIn predicate on the "age" field.
func AgeNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAge, vs...))
}

// AgeGT applies the GT predicate on the "age" field.
func AgeGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldAge, v))
}

// AgeGTE applies the GTE predicate on the "age" field.
func AgeGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAge, v))
}

// AgeLT applies the LT predicate on the "age" field.
func AgeLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldAge, v))
}

// AgeLTE applies the LTE predicate on the "age" field.
func AgeLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAge, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameIsNil applies the IsNil predicate on the "nickname" field.
func NicknameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldNickname))
}

// NicknameNotNil applies the NotNil predicate on the "nickname" field.
func NicknameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldNickname))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldNickname, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldScore, v))
}

// ScoreIsNil applies the IsNil predicate on the "score" field.
func ScoreIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldScore))
}

// ScoreNotNil applies the NotNil predicate on the "score" field.
func ScoreNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldScore))
}

// IsVerifiedEQ applies the EQ predicate on the "is_verified" field.
func IsVerifiedEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsVerified, v))
}

// IsVerifiedNEQ applies the NEQ predicate on the "is_verified" field.
func IsVerifiedNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsVerified, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTags))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPassword, v))
}

// TestUUIDEQ applies the EQ predicate on the "test_uuid" field.
func TestUUIDEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTestUUID, v))
}

// TestUUIDNEQ applies the NEQ predicate on the "test_uuid" field.
func TestUUIDNEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTestUUID, v))
}

// TestUUIDIn applies the In predicate on the "test_uuid" field.
func TestUUIDIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldTestUUID, vs...))
}

// TestUUIDNotIn applies the NotIn predicate on the "test_uuid" field.
func TestUUIDNotIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTestUUID, vs...))
}

// TestUUIDGT applies the GT predicate on the "test_uuid" field.
func TestUUIDGT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldTestUUID, v))
}

// TestUUIDGTE applies the GTE predicate on the "test_uuid" field.
func TestUUIDGTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTestUUID, v))
}

// TestUUIDLT applies the LT predicate on the "test_uuid" field.
func TestUUIDLT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldTestUUID, v))
}

// TestUUIDLTE applies the LTE predicate on the "test_uuid" field.
func TestUUIDLTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTestUUID, v))
}

// TestNillableUUIDEQ applies the EQ predicate on the "test_nillable_uuid" field.
func TestNillableUUIDEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTestNillableUUID, v))
}

// TestNillableUUIDNEQ applies the NEQ predicate on the "test_nillable_uuid" field.
func TestNillableUUIDNEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTestNillableUUID, v))
}

// TestNillableUUIDIn applies the In predicate on the "test_nillable_uuid" field.
func TestNillableUUIDIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldTestNillableUUID, vs...))
}

// TestNillableUUIDNotIn applies the NotIn predicate on the "test_nillable_uuid" field.
func TestNillableUUIDNotIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTestNillableUUID, vs...))
}

// TestNillableUUIDGT applies the GT predicate on the "test_nillable_uuid" field.
func TestNillableUUIDGT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldTestNillableUUID, v))
}

// TestNillableUUIDGTE applies the GTE predicate on the "test_nillable_uuid" field.
func TestNillableUUIDGTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTestNillableUUID, v))
}

// TestNillableUUIDLT applies the LT predicate on the "test_nillable_uuid" field.
func TestNillableUUIDLT(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldTestNillableUUID, v))
}

// TestNillableUUIDLTE applies the LTE predicate on the "test_nillable_uuid" field.
func TestNillableUUIDLTE(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTestNillableUUID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.User {
	return predicate.User(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldStatus, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v auth.UserRole) predicate.User {
	vc := v
	return predicate.User(sql.FieldEQ(FieldRole, vc))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v auth.UserRole) predicate.User {
	vc := v
	return predicate.User(sql.FieldNEQ(FieldRole, vc))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...auth.UserRole) predicate.User {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.User(sql.FieldIn(FieldRole, v...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...auth.UserRole) predicate.User {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.User(sql.FieldNotIn(FieldRole, v...))
}

// RemoteTokenEQ applies the EQ predicate on the "remote_token" field.
func RemoteTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRemoteToken, v))
}

// RemoteTokenNEQ applies the NEQ predicate on the "remote_token" field.
func RemoteTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRemoteToken, v))
}

// RemoteTokenIn applies the In predicate on the "remote_token" field.
func RemoteTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldRemoteToken, vs...))
}

// RemoteTokenNotIn applies the NotIn predicate on the "remote_token" field.
func RemoteTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRemoteToken, vs...))
}

// RemoteTokenGT applies the GT predicate on the "remote_token" field.
func RemoteTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldRemoteToken, v))
}

// RemoteTokenGTE applies the GTE predicate on the "remote_token" field.
func RemoteTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRemoteToken, v))
}

// RemoteTokenLT applies the LT predicate on the "remote_token" field.
func RemoteTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldRemoteToken, v))
}

// RemoteTokenLTE applies the LTE predicate on the "remote_token" field.
func RemoteTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRemoteToken, v))
}

// RemoteTokenContains applies the Contains predicate on the "remote_token" field.
func RemoteTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldRemoteToken, v))
}

// RemoteTokenHasPrefix applies the HasPrefix predicate on the "remote_token" field.
func RemoteTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldRemoteToken, v))
}

// RemoteTokenHasSuffix applies the HasSuffix predicate on the "remote_token" field.
func RemoteTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldRemoteToken, v))
}

// RemoteTokenEqualFold applies the EqualFold predicate on the "remote_token" field.
func RemoteTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldRemoteToken, v))
}

// RemoteTokenContainsFold applies the ContainsFold predicate on the "remote_token" field.
func RemoteTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldRemoteToken, v))
}

// TestTimeEQ applies the EQ predicate on the "test_time" field.
func TestTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTestTime, v))
}

// TestTimeNEQ applies the NEQ predicate on the "test_time" field.
func TestTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTestTime, v))
}

// TestTimeIn applies the In predicate on the "test_time" field.
func TestTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldTestTime, vs...))
}

// TestTimeNotIn applies the NotIn predicate on the "test_time" field.
func TestTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTestTime, vs...))
}

// TestTimeGT applies the GT predicate on the "test_time" field.
func TestTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldTestTime, v))
}

// TestTimeGTE applies the GTE predicate on the "test_time" field.
func TestTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTestTime, v))
}

// TestTimeLT applies the LT predicate on the "test_time" field.
func TestTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldTestTime, v))
}

// TestTimeLTE applies the LTE predicate on the "test_time" field.
func TestTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTestTime, v))
}

// TestTimeIsNil applies the IsNil predicate on the "test_time" field.
func TestTimeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTestTime))
}

// TestTimeNotNil applies the NotNil predicate on the "test_time" field.
func TestTimeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTestTime))
}

// LastLoginIPEQ applies the EQ predicate on the "last_login_ip" field.
func LastLoginIPEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLoginIP, v))
}

// LastLoginIPNEQ applies the NEQ predicate on the "last_login_ip" field.
func LastLoginIPNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastLoginIP, v))
}

// LastLoginIPIn applies the In predicate on the "last_login_ip" field.
func LastLoginIPIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastLoginIP, vs...))
}

// LastLoginIPNotIn applies the NotIn predicate on the "last_login_ip" field.
func LastLoginIPNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastLoginIP, vs...))
}

// LastLoginIPGT applies the GT predicate on the "last_login_ip" field.
func LastLoginIPGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastLoginIP, v))
}

// LastLoginIPGTE applies the GTE predicate on the "last_login_ip" field.
func LastLoginIPGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastLoginIP, v))
}

// LastLoginIPLT applies the LT predicate on the "last_login_ip" field.
func LastLoginIPLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastLoginIP, v))
}

// LastLoginIPLTE applies the LTE predicate on the "last_login_ip" field.
func LastLoginIPLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastLoginIP, v))
}

// LastLoginIPContains applies the Contains predicate on the "last_login_ip" field.
func LastLoginIPContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLastLoginIP, v))
}

// LastLoginIPHasPrefix applies the HasPrefix predicate on the "last_login_ip" field.
func LastLoginIPHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLastLoginIP, v))
}

// LastLoginIPHasSuffix applies the HasSuffix predicate on the "last_login_ip" field.
func LastLoginIPHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLastLoginIP, v))
}

// LastLoginIPIsNil applies the IsNil predicate on the "last_login_ip" field.
func LastLoginIPIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLastLoginIP))
}

// LastLoginIPNotNil applies the NotNil predicate on the "last_login_ip" field.
func LastLoginIPNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLastLoginIP))
}

// LastLoginIPEqualFold applies the EqualFold predicate on the "last_login_ip" field.
func LastLoginIPEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLastLoginIP, v))
}

// LastLoginIPContainsFold applies the ContainsFold predicate on the "last_login_ip" field.
func LastLoginIPContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLastLoginIP, v))
}

// VerificationCodeEQ applies the EQ predicate on the "verification_code" field.
func VerificationCodeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerificationCode, v))
}

// VerificationCodeNEQ applies the NEQ predicate on the "verification_code" field.
func VerificationCodeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldVerificationCode, v))
}

// VerificationCodeIn applies the In predicate on the "verification_code" field.
func VerificationCodeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldVerificationCode, vs...))
}

// VerificationCodeNotIn applies the NotIn predicate on the "verification_code" field.
func VerificationCodeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldVerificationCode, vs...))
}

// VerificationCodeGT applies the GT predicate on the "verification_code" field.
func VerificationCodeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldVerificationCode, v))
}

// VerificationCodeGTE applies the GTE predicate on the "verification_code" field.
func VerificationCodeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldVerificationCode, v))
}

// VerificationCodeLT applies the LT predicate on the "verification_code" field.
func VerificationCodeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldVerificationCode, v))
}

// VerificationCodeLTE applies the LTE predicate on the "verification_code" field.
func VerificationCodeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldVerificationCode, v))
}

// VerificationCodeContains applies the Contains predicate on the "verification_code" field.
func VerificationCodeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldVerificationCode, v))
}

// VerificationCodeHasPrefix applies the HasPrefix predicate on the "verification_code" field.
func VerificationCodeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldVerificationCode, v))
}

// VerificationCodeHasSuffix applies the HasSuffix predicate on the "verification_code" field.
func VerificationCodeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldVerificationCode, v))
}

// VerificationCodeIsNil applies the IsNil predicate on the "verification_code" field.
func VerificationCodeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldVerificationCode))
}

// VerificationCodeNotNil applies the NotNil predicate on the "verification_code" field.
func VerificationCodeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldVerificationCode))
}

// VerificationCodeEqualFold applies the EqualFold predicate on the "verification_code" field.
func VerificationCodeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldVerificationCode, v))
}

// VerificationCodeContainsFold applies the ContainsFold predicate on the "verification_code" field.
func VerificationCodeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldVerificationCode, v))
}

// InternalIDEQ applies the EQ predicate on the "internal_id" field.
func InternalIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldInternalID, v))
}

// InternalIDNEQ applies the NEQ predicate on the "internal_id" field.
func InternalIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldInternalID, v))
}

// InternalIDIn applies the In predicate on the "internal_id" field.
func InternalIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldInternalID, vs...))
}

// InternalIDNotIn applies the NotIn predicate on the "internal_id" field.
func InternalIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldInternalID, vs...))
}

// InternalIDGT applies the GT predicate on the "internal_id" field.
func InternalIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldInternalID, v))
}

// InternalIDGTE applies the GTE predicate on the "internal_id" field.
func InternalIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldInternalID, v))
}

// InternalIDLT applies the LT predicate on the "internal_id" field.
func InternalIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldInternalID, v))
}

// InternalIDLTE applies the LTE predicate on the "internal_id" field.
func InternalIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldInternalID, v))
}

// InternalIDIsNil applies the IsNil predicate on the "internal_id" field.
func InternalIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldInternalID))
}

// InternalIDNotNil applies the NotNil predicate on the "internal_id" field.
func InternalIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldInternalID))
}

// HasPosts applies the HasEdge predicate on the "posts" edge.
func HasPosts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostsWith applies the HasEdge predicate on the "posts" edge with a given conditions (other predicates).
func HasPostsWith(preds ...predicate.Post) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFollowers applies the HasEdge predicate on the "followers" edge.
func HasFollowers() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, FollowersTable, FollowersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFollowersWith applies the HasEdge predicate on the "followers" edge with a given conditions (other predicates).
func HasFollowersWith(preds ...predicate.User) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newFollowersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCoAuthorsArchive applies the HasEdge predicate on the "co_authors_archive" edge.
func HasCoAuthorsArchive() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, CoAuthorsArchiveTable, CoAuthorsArchivePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoAuthorsArchiveWith applies the HasEdge predicate on the "co_authors_archive" edge with a given conditions (other predicates).
func HasCoAuthorsArchiveWith(preds ...predicate.User) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCoAuthorsArchiveStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFriends applies the HasEdge predicate on the "friends" edge.
func HasFriends() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, FriendsTable, FriendsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFriendsWith applies the HasEdge predicate on the "friends" edge with a given conditions (other predicates).
func HasFriendsWith(preds ...predicate.User) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newFriendsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
