// Code generated by lazyent. DO NOT EDIT.
package service

import (
	pb "github.com/Cromemadnd/lazyent/internal/tests/testenv/api/v1"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/biz"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/pkg/auth"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func BizGroupToProto(b *biz.Group) (*pb.Group, error) {
	if b == nil {
		return nil, nil
	}
	var users []*pb.User
	for _, item := range b.Users {
		v, err := BizUserToProto(item)
		if err != nil {
			return nil, err
		}
		users = append(users, v)
	}
	return &pb.Group{
		Uuid:      b.UUID,
		CreatedAt: timestamppb.New(b.CreatedAt),
		UpdatedAt: timestamppb.New(b.UpdatedAt),
		Name:      b.Name,
		Users:     users,
	}, nil
}

func ProtoGroupToBiz(p *pb.Group) (*biz.Group, error) {
	if p == nil {
		return nil, nil
	}
	var users []*biz.User
	for _, item := range p.Users {
		v, err := ProtoUserToBiz(item)
		if err != nil {
			return nil, err
		}
		users = append(users, v)
	}
	return &biz.Group{
		GroupBase: biz.GroupBase{
			UUID:      p.Uuid,
			CreatedAt: p.CreatedAt.AsTime(),
			UpdatedAt: p.UpdatedAt.AsTime(),
			Name:      p.Name,
			Users:     users,
		},
	}, nil
}

func BizPostToProto(b *biz.Post) (*pb.Post, error) {
	if b == nil {
		return nil, nil
	}

	return &pb.Post{
		Uuid:      b.UUID,
		CreatedAt: timestamppb.New(b.CreatedAt),
		UpdatedAt: timestamppb.New(b.UpdatedAt),
		Title:     b.Title,
		Content:   b.Content,
		Author:    b.Author.UUID,
	}, nil
}

func ProtoPostToBiz(p *pb.Post) (*biz.Post, error) {
	if p == nil {
		return nil, nil
	}
	return &biz.Post{
		PostBase: biz.PostBase{
			UUID:      p.Uuid,
			CreatedAt: p.CreatedAt.AsTime(),
			UpdatedAt: p.UpdatedAt.AsTime(),
			Title:     p.Title,
			Content:   p.Content,
			Author:    &biz.User{UserBase: biz.UserBase{UUID: p.Author}},
		},
	}, nil
}

func BizUserToProto(b *biz.User) (*pb.User, error) {
	if b == nil {
		return nil, nil
	}

	var postIds []string
	for _, item := range b.PostIDs {
		postIds = append(postIds, item)
	}
	var groups []*pb.Group
	for _, item := range b.Groups {
		v, err := BizGroupToProto(item)
		if err != nil {
			return nil, err
		}
		groups = append(groups, v)
	}
	return &pb.User{
		Uuid:             b.UUID,
		CreatedAt:        timestamppb.New(b.CreatedAt),
		UpdatedAt:        timestamppb.New(b.UpdatedAt),
		Name:             b.Name,
		Age:              int32(b.Age),
		Nickname:         b.Nickname,
		UserScore:        uint32(b.UserScore),
		IsVerified:       b.IsVerified,
		Tags:             b.Tags,
		TestUuid:         b.TestUUID,
		TestNillableUuid: b.TestNillableUUID,
		Status:           BizUserStatusToProto(b.Status),
		Role:             string(b.Role),
		PostIds:          postIds,
		Groups:           groups,
	}, nil
}

func ProtoUserToBiz(p *pb.User) (*biz.User, error) {
	if p == nil {
		return nil, nil
	}

	var postIds []string
	for _, item := range p.PostIds {
		postIds = append(postIds, item)
	}
	var groups []*biz.Group
	for _, item := range p.Groups {
		v, err := ProtoGroupToBiz(item)
		if err != nil {
			return nil, err
		}
		groups = append(groups, v)
	}
	return &biz.User{
		UserBase: biz.UserBase{
			UUID:             p.Uuid,
			CreatedAt:        p.CreatedAt.AsTime(),
			UpdatedAt:        p.UpdatedAt.AsTime(),
			Name:             p.Name,
			Age:              int(p.Age),
			Nickname:         p.Nickname,
			UserScore:        uint8(p.UserScore),
			IsVerified:       p.IsVerified,
			Tags:             p.Tags,
			TestUUID:         p.TestUuid,
			TestNillableUUID: p.TestNillableUuid,
			Status:           ProtoUserStatusToBiz(p.Status),
			Role:             auth.UserRole(p.Role),
			PostIDs:          postIds,
			Groups:           groups,
		},
	}, nil
}

func BizUserStatusToProto(e biz.UserStatus) pb.UserStatus {
	switch e {
	case biz.UserStatusUnspecified:
		return pb.UserStatus_USERSTATUS_UNSPECIFIED
	case biz.UserStatusActive:
		return pb.UserStatus_USERSTATUS_ACTIVE
	case biz.UserStatusInactive:
		return pb.UserStatus_USERSTATUS_INACTIVE
	case biz.UserStatusBanned:
		return pb.UserStatus_USERSTATUS_BANNED
	default:
		return pb.UserStatus_USERSTATUS_UNSPECIFIED
	}
}

func ProtoUserStatusToBiz(e pb.UserStatus) biz.UserStatus {
	switch e {
	case pb.UserStatus_USERSTATUS_UNSPECIFIED:
		return biz.UserStatusUnspecified
	case pb.UserStatus_USERSTATUS_ACTIVE:
		return biz.UserStatusActive
	case pb.UserStatus_USERSTATUS_INACTIVE:
		return biz.UserStatusInactive
	case pb.UserStatus_USERSTATUS_BANNED:
		return biz.UserStatusBanned
	default:
		return biz.UserStatusUnspecified
	}
}
