// Code generated by lazyent. DO NOT EDIT.
package biz

import (
	"time"

	"github.com/Cromemadnd/lazyent/internal/tests/testenv/pkg/auth"
	"github.com/google/uuid"
)

// GroupBase 是 Group 的基础结构体，包含自动生成的字段定义
type GroupBase struct {
	UUID      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UsersTest []*User
}

// PostBase 是 Post 的基础结构体，包含自动生成的字段定义
type PostBase struct {
	UUID             string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Title            string
	Content          string
	Slug             string
	ManagementKey    string
	Summary          string
	ExtraData        string
	Author           *User
	CoAuthors        []*User
	RelevantGroupsID []uuid.UUID
	Followers        []*User
	CoAuthorsArchive []*User
}

// Status 枚举定义
type UserStatus int32

const (
	UserStatusUnspecified UserStatus = 0
	UserStatusActive      UserStatus = 1
	UserStatusInactive    UserStatus = 2
	UserStatusBanned      UserStatus = 3
)

func (e UserStatus) String() string {
	switch e {
	case UserStatusUnspecified:
		return "UNSPECIFIED"
	case UserStatusActive:
		return "ACTIVE"
	case UserStatusInactive:
		return "INACTIVE"
	case UserStatusBanned:
		return "BANNED"
	default:
		return "UNKNOWN"
	}
}

// UserBase 是 User 的基础结构体，包含自动生成的字段定义
type UserBase struct {
	UUID             string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	Age              int
	Nickname         string
	UserScore        uint8
	IsVerified       bool
	Tags             []string
	Password         string
	TestUUID         string
	TestNillableUUID string
	Status           UserStatus
	Role             auth.UserRole
	RemoteToken      string
	ExtUser          *auth.User
	TestTime         time.Time
	LastLoginIP      string
	VerificationCode string
	PostIDs          []uuid.UUID
	Groups           []*Group
	Followers        []*User
	CoAuthorsArchive []*User
	Friends          []*User
}
