// File generated by lazyent. DO NOT EDIT.
package biz

import (
	"time"
)

// GroupBase 是 Group 的基础结构体，包含自动生成的字段定义
type GroupBase struct {
	UUID      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string

	Users []*User
}

// PostBase 是 Post 的基础结构体，包含自动生成的字段定义
type PostBase struct {
	UUID      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Content   string

	Author *User
}

// Status 枚举定义
type UserStatus int32

const (
	UserStatusActive   UserStatus = 1
	UserStatusInactive UserStatus = 4
	UserStatusBanned   UserStatus = 3
)

func (e UserStatus) String() string {
	switch e {
	case UserStatusActive:
		return "ACTIVE"
	case UserStatusInactive:
		return "INACTIVE"
	case UserStatusBanned:
		return "BANNED"
	default:
		return "UNKNOWN"
	}
}

// UserBase 是 User 的基础结构体，包含自动生成的字段定义
type UserBase struct {
	UUID       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Age        int
	Nickname   string
	UserScore  uint8
	IsVerified bool
	Tags       []string
	Status     UserStatus

	PostIDs []string

	Groups []*Group

	Friends []*User
}
