// File generated by lazyent. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dtos_gen.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USERSTATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USERSTATUS_ACTIVE      UserStatus = 1
	UserStatus_USERSTATUS_INACTIVE    UserStatus = 4
	UserStatus_USERSTATUS_BANNED      UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USERSTATUS_UNSPECIFIED",
		1: "USERSTATUS_ACTIVE",
		4: "USERSTATUS_INACTIVE",
		3: "USERSTATUS_BANNED",
	}
	UserStatus_value = map[string]int32{
		"USERSTATUS_UNSPECIFIED": 0,
		"USERSTATUS_ACTIVE":      1,
		"USERSTATUS_INACTIVE":    4,
		"USERSTATUS_BANNED":      3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dtos_gen_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_dtos_gen_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_dtos_gen_proto_rawDescGZIP(), []int{0}
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // 数据库主键
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Users         []*User                `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_dtos_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_dtos_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_dtos_gen_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // 数据库主键
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_dtos_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_dtos_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_dtos_gen_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // 数据库主键
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Nickname      string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UserScore     uint32                 `protobuf:"varint,7,opt,name=user_score,json=userScore,proto3" json:"user_score,omitempty"`
	IsVerified    bool                   `protobuf:"varint,8,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"` // 用户标签
	Status        UserStatus             `protobuf:"varint,10,opt,name=status,proto3,enum=user.v1.UserStatus" json:"status,omitempty"`
	PostIds       []string               `protobuf:"bytes,11,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	Groups        []*Group               `protobuf:"bytes,12,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_dtos_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_dtos_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_dtos_gen_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetUserScore() uint32 {
	if x != nil {
		return x.UserScore
	}
	return 0
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USERSTATUS_UNSPECIFIED
}

func (x *User) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *User) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_dtos_gen_proto protoreflect.FileDescriptor

const file_dtos_gen_proto_rawDesc = "" +
	"\n" +
	"\x0edtos_gen.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xdd\x01\n" +
	"\x05Group\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\x04name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x00R\x04name\x12#\n" +
	"\x05users\x18\x05 \x03(\v2\r.user.v1.UserR\x05users\"\xf5\x01\n" +
	"\x04Post\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\x05title\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x00R\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12 \n" +
	"\x06author\x18\x06 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06author\"\xd0\x03\n" +
	"\x04User\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x19\n" +
	"\x03age\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x03age\x12(\n" +
	"\bnickname\x18\x06 \x01(\tB\f\xfaB\tr\a\x10\x02\x18\x14\xd0\x01\x01R\bnickname\x12\x1d\n" +
	"\n" +
	"user_score\x18\a \x01(\rR\tuserScore\x12\x1f\n" +
	"\vis_verified\x18\b \x01(\bR\n" +
	"isVerified\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x125\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x13.user.v1.UserStatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12(\n" +
	"\bpost_ids\x18\v \x03(\tB\r\xfaB\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\apostIds\x12&\n" +
	"\x06groups\x18\f \x03(\v2\x0e.user.v1.GroupR\x06groups*o\n" +
	"\n" +
	"UserStatus\x12\x1a\n" +
	"\x16USERSTATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11USERSTATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13USERSTATUS_INACTIVE\x10\x04\x12\x15\n" +
	"\x11USERSTATUS_BANNED\x10\x03B\x1dZ\x1blazyent-test-app/user/v1;v1b\x06proto3"

var (
	file_dtos_gen_proto_rawDescOnce sync.Once
	file_dtos_gen_proto_rawDescData []byte
)

func file_dtos_gen_proto_rawDescGZIP() []byte {
	file_dtos_gen_proto_rawDescOnce.Do(func() {
		file_dtos_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtos_gen_proto_rawDesc), len(file_dtos_gen_proto_rawDesc)))
	})
	return file_dtos_gen_proto_rawDescData
}

var file_dtos_gen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dtos_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dtos_gen_proto_goTypes = []any{
	(UserStatus)(0),               // 0: user.v1.UserStatus
	(*Group)(nil),                 // 1: user.v1.Group
	(*Post)(nil),                  // 2: user.v1.Post
	(*User)(nil),                  // 3: user.v1.User
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_dtos_gen_proto_depIdxs = []int32{
	4, // 0: user.v1.Group.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: user.v1.Group.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: user.v1.Group.users:type_name -> user.v1.User
	4, // 3: user.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: user.v1.Post.updated_at:type_name -> google.protobuf.Timestamp
	4, // 5: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	4, // 6: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 7: user.v1.User.status:type_name -> user.v1.UserStatus
	1, // 8: user.v1.User.groups:type_name -> user.v1.Group
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_dtos_gen_proto_init() }
func file_dtos_gen_proto_init() {
	if File_dtos_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtos_gen_proto_rawDesc), len(file_dtos_gen_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtos_gen_proto_goTypes,
		DependencyIndexes: file_dtos_gen_proto_depIdxs,
		EnumInfos:         file_dtos_gen_proto_enumTypes,
		MessageInfos:      file_dtos_gen_proto_msgTypes,
	}.Build()
	File_dtos_gen_proto = out.File
	file_dtos_gen_proto_goTypes = nil
	file_dtos_gen_proto_depIdxs = nil
}
