//go:build ignore

package main

import (
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/Cromemadnd/lazyent"
)

func main() {
	// 1. Define Config
	opts := []entc.Option{
		entc.Extensions(lazyent.NewExtension(
			lazyent.Config{
				ProtoOut:     "internal/tests/testenv/api/v1",
				BizOut:       "internal/tests/testenv/app/user/internal/biz",
				ServiceOut:   "internal/tests/testenv/app/user/internal/service",
				DataOut:      "internal/tests/testenv/app/user/internal/data",
				ProtoPackage: "user.v1",
				GoPackage:    "lazyent-test-app/user/v1;v1",
				SingleFile:   true,
			},
		)),
	}

	// 执行 Ent 代码生成
	// 假设 schema 文件位于 ./schema 目录
	if err := entc.Generate("./schema", &gen.Config{
		Header:  "// Code generated by ent, DO NOT EDIT.",
		Package: "github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent",
	}, opts...); err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
