// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/group"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/post"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/predicate"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/user"
	"github.com/google/uuid"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdate) SetContent(v string) *PostUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdate) SetNillableContent(v *string) *PostUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdate) SetSlug(v string) *PostUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSlug(v *string) *PostUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *PostUpdate) ClearSlug() *PostUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetInternalCode sets the "internal_code" field.
func (_u *PostUpdate) SetInternalCode(v string) *PostUpdate {
	_u.mutation.SetInternalCode(v)
	return _u
}

// SetNillableInternalCode sets the "internal_code" field if the given value is not nil.
func (_u *PostUpdate) SetNillableInternalCode(v *string) *PostUpdate {
	if v != nil {
		_u.SetInternalCode(*v)
	}
	return _u
}

// ClearInternalCode clears the value of the "internal_code" field.
func (_u *PostUpdate) ClearInternalCode() *PostUpdate {
	_u.mutation.ClearInternalCode()
	return _u
}

// SetManagementKey sets the "management_key" field.
func (_u *PostUpdate) SetManagementKey(v string) *PostUpdate {
	_u.mutation.SetManagementKey(v)
	return _u
}

// SetNillableManagementKey sets the "management_key" field if the given value is not nil.
func (_u *PostUpdate) SetNillableManagementKey(v *string) *PostUpdate {
	if v != nil {
		_u.SetManagementKey(*v)
	}
	return _u
}

// ClearManagementKey clears the value of the "management_key" field.
func (_u *PostUpdate) ClearManagementKey() *PostUpdate {
	_u.mutation.ClearManagementKey()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostUpdate) SetSummary(v string) *PostUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSummary(v *string) *PostUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *PostUpdate) ClearSummary() *PostUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetExtraData sets the "extra_data" field.
func (_u *PostUpdate) SetExtraData(v string) *PostUpdate {
	_u.mutation.SetExtraData(v)
	return _u
}

// SetNillableExtraData sets the "extra_data" field if the given value is not nil.
func (_u *PostUpdate) SetNillableExtraData(v *string) *PostUpdate {
	if v != nil {
		_u.SetExtraData(*v)
	}
	return _u
}

// ClearExtraData clears the value of the "extra_data" field.
func (_u *PostUpdate) ClearExtraData() *PostUpdate {
	_u.mutation.ClearExtraData()
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *PostUpdate) SetAuthorID(id uuid.UUID) *PostUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PostUpdate) SetAuthor(v *User) *PostUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddCoAuthorIDs adds the "co_authors" edge to the User entity by IDs.
func (_u *PostUpdate) AddCoAuthorIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddCoAuthorIDs(ids...)
	return _u
}

// AddCoAuthors adds the "co_authors" edges to the User entity.
func (_u *PostUpdate) AddCoAuthors(v ...*User) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCoAuthorIDs(ids...)
}

// AddRelevantGroupIDs adds the "relevant_groups" edge to the Group entity by IDs.
func (_u *PostUpdate) AddRelevantGroupIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddRelevantGroupIDs(ids...)
	return _u
}

// AddRelevantGroups adds the "relevant_groups" edges to the Group entity.
func (_u *PostUpdate) AddRelevantGroups(v ...*Group) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelevantGroupIDs(ids...)
}

// AddFollowerIDs adds the "followers" edge to the User entity by IDs.
func (_u *PostUpdate) AddFollowerIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddFollowerIDs(ids...)
	return _u
}

// AddFollowers adds the "followers" edges to the User entity.
func (_u *PostUpdate) AddFollowers(v ...*User) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFollowerIDs(ids...)
}

// AddCoAuthorsArchiveIDs adds the "co_authors_archive" edge to the User entity by IDs.
func (_u *PostUpdate) AddCoAuthorsArchiveIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddCoAuthorsArchiveIDs(ids...)
	return _u
}

// AddCoAuthorsArchive adds the "co_authors_archive" edges to the User entity.
func (_u *PostUpdate) AddCoAuthorsArchive(v ...*User) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCoAuthorsArchiveIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PostUpdate) ClearAuthor() *PostUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCoAuthors clears all "co_authors" edges to the User entity.
func (_u *PostUpdate) ClearCoAuthors() *PostUpdate {
	_u.mutation.ClearCoAuthors()
	return _u
}

// RemoveCoAuthorIDs removes the "co_authors" edge to User entities by IDs.
func (_u *PostUpdate) RemoveCoAuthorIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveCoAuthorIDs(ids...)
	return _u
}

// RemoveCoAuthors removes "co_authors" edges to User entities.
func (_u *PostUpdate) RemoveCoAuthors(v ...*User) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCoAuthorIDs(ids...)
}

// ClearRelevantGroups clears all "relevant_groups" edges to the Group entity.
func (_u *PostUpdate) ClearRelevantGroups() *PostUpdate {
	_u.mutation.ClearRelevantGroups()
	return _u
}

// RemoveRelevantGroupIDs removes the "relevant_groups" edge to Group entities by IDs.
func (_u *PostUpdate) RemoveRelevantGroupIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveRelevantGroupIDs(ids...)
	return _u
}

// RemoveRelevantGroups removes "relevant_groups" edges to Group entities.
func (_u *PostUpdate) RemoveRelevantGroups(v ...*Group) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelevantGroupIDs(ids...)
}

// ClearFollowers clears all "followers" edges to the User entity.
func (_u *PostUpdate) ClearFollowers() *PostUpdate {
	_u.mutation.ClearFollowers()
	return _u
}

// RemoveFollowerIDs removes the "followers" edge to User entities by IDs.
func (_u *PostUpdate) RemoveFollowerIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveFollowerIDs(ids...)
	return _u
}

// RemoveFollowers removes "followers" edges to User entities.
func (_u *PostUpdate) RemoveFollowers(v ...*User) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFollowerIDs(ids...)
}

// ClearCoAuthorsArchive clears all "co_authors_archive" edges to the User entity.
func (_u *PostUpdate) ClearCoAuthorsArchive() *PostUpdate {
	_u.mutation.ClearCoAuthorsArchive()
	return _u
}

// RemoveCoAuthorsArchiveIDs removes the "co_authors_archive" edge to User entities by IDs.
func (_u *PostUpdate) RemoveCoAuthorsArchiveIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveCoAuthorsArchiveIDs(ids...)
	return _u
}

// RemoveCoAuthorsArchive removes "co_authors_archive" edges to User entities.
func (_u *PostUpdate) RemoveCoAuthorsArchive(v ...*User) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCoAuthorsArchiveIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.author"`)
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(post.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.InternalCode(); ok {
		_spec.SetField(post.FieldInternalCode, field.TypeString, value)
	}
	if _u.mutation.InternalCodeCleared() {
		_spec.ClearField(post.FieldInternalCode, field.TypeString)
	}
	if value, ok := _u.mutation.ManagementKey(); ok {
		_spec.SetField(post.FieldManagementKey, field.TypeString, value)
	}
	if _u.mutation.ManagementKeyCleared() {
		_spec.ClearField(post.FieldManagementKey, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(post.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ExtraData(); ok {
		_spec.SetField(post.FieldExtraData, field.TypeString, value)
	}
	if _u.mutation.ExtraDataCleared() {
		_spec.ClearField(post.FieldExtraData, field.TypeString)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoAuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsTable,
			Columns: []string{post.CoAuthorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCoAuthorsIDs(); len(nodes) > 0 && !_u.mutation.CoAuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsTable,
			Columns: []string{post.CoAuthorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoAuthorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsTable,
			Columns: []string{post.CoAuthorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelevantGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.RelevantGroupsTable,
			Columns: []string{post.RelevantGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelevantGroupsIDs(); len(nodes) > 0 && !_u.mutation.RelevantGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.RelevantGroupsTable,
			Columns: []string{post.RelevantGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelevantGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.RelevantGroupsTable,
			Columns: []string{post.RelevantGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.FollowersTable,
			Columns: []string{post.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFollowersIDs(); len(nodes) > 0 && !_u.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.FollowersTable,
			Columns: []string{post.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.FollowersTable,
			Columns: []string{post.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoAuthorsArchiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsArchiveTable,
			Columns: []string{post.CoAuthorsArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCoAuthorsArchiveIDs(); len(nodes) > 0 && !_u.mutation.CoAuthorsArchiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsArchiveTable,
			Columns: []string{post.CoAuthorsArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoAuthorsArchiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsArchiveTable,
			Columns: []string{post.CoAuthorsArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdateOne) SetContent(v string) *PostUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableContent(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdateOne) SetSlug(v string) *PostUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSlug(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *PostUpdateOne) ClearSlug() *PostUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetInternalCode sets the "internal_code" field.
func (_u *PostUpdateOne) SetInternalCode(v string) *PostUpdateOne {
	_u.mutation.SetInternalCode(v)
	return _u
}

// SetNillableInternalCode sets the "internal_code" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableInternalCode(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetInternalCode(*v)
	}
	return _u
}

// ClearInternalCode clears the value of the "internal_code" field.
func (_u *PostUpdateOne) ClearInternalCode() *PostUpdateOne {
	_u.mutation.ClearInternalCode()
	return _u
}

// SetManagementKey sets the "management_key" field.
func (_u *PostUpdateOne) SetManagementKey(v string) *PostUpdateOne {
	_u.mutation.SetManagementKey(v)
	return _u
}

// SetNillableManagementKey sets the "management_key" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableManagementKey(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetManagementKey(*v)
	}
	return _u
}

// ClearManagementKey clears the value of the "management_key" field.
func (_u *PostUpdateOne) ClearManagementKey() *PostUpdateOne {
	_u.mutation.ClearManagementKey()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostUpdateOne) SetSummary(v string) *PostUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSummary(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *PostUpdateOne) ClearSummary() *PostUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetExtraData sets the "extra_data" field.
func (_u *PostUpdateOne) SetExtraData(v string) *PostUpdateOne {
	_u.mutation.SetExtraData(v)
	return _u
}

// SetNillableExtraData sets the "extra_data" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableExtraData(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetExtraData(*v)
	}
	return _u
}

// ClearExtraData clears the value of the "extra_data" field.
func (_u *PostUpdateOne) ClearExtraData() *PostUpdateOne {
	_u.mutation.ClearExtraData()
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *PostUpdateOne) SetAuthorID(id uuid.UUID) *PostUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PostUpdateOne) SetAuthor(v *User) *PostUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddCoAuthorIDs adds the "co_authors" edge to the User entity by IDs.
func (_u *PostUpdateOne) AddCoAuthorIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddCoAuthorIDs(ids...)
	return _u
}

// AddCoAuthors adds the "co_authors" edges to the User entity.
func (_u *PostUpdateOne) AddCoAuthors(v ...*User) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCoAuthorIDs(ids...)
}

// AddRelevantGroupIDs adds the "relevant_groups" edge to the Group entity by IDs.
func (_u *PostUpdateOne) AddRelevantGroupIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddRelevantGroupIDs(ids...)
	return _u
}

// AddRelevantGroups adds the "relevant_groups" edges to the Group entity.
func (_u *PostUpdateOne) AddRelevantGroups(v ...*Group) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelevantGroupIDs(ids...)
}

// AddFollowerIDs adds the "followers" edge to the User entity by IDs.
func (_u *PostUpdateOne) AddFollowerIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddFollowerIDs(ids...)
	return _u
}

// AddFollowers adds the "followers" edges to the User entity.
func (_u *PostUpdateOne) AddFollowers(v ...*User) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFollowerIDs(ids...)
}

// AddCoAuthorsArchiveIDs adds the "co_authors_archive" edge to the User entity by IDs.
func (_u *PostUpdateOne) AddCoAuthorsArchiveIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddCoAuthorsArchiveIDs(ids...)
	return _u
}

// AddCoAuthorsArchive adds the "co_authors_archive" edges to the User entity.
func (_u *PostUpdateOne) AddCoAuthorsArchive(v ...*User) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCoAuthorsArchiveIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PostUpdateOne) ClearAuthor() *PostUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCoAuthors clears all "co_authors" edges to the User entity.
func (_u *PostUpdateOne) ClearCoAuthors() *PostUpdateOne {
	_u.mutation.ClearCoAuthors()
	return _u
}

// RemoveCoAuthorIDs removes the "co_authors" edge to User entities by IDs.
func (_u *PostUpdateOne) RemoveCoAuthorIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveCoAuthorIDs(ids...)
	return _u
}

// RemoveCoAuthors removes "co_authors" edges to User entities.
func (_u *PostUpdateOne) RemoveCoAuthors(v ...*User) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCoAuthorIDs(ids...)
}

// ClearRelevantGroups clears all "relevant_groups" edges to the Group entity.
func (_u *PostUpdateOne) ClearRelevantGroups() *PostUpdateOne {
	_u.mutation.ClearRelevantGroups()
	return _u
}

// RemoveRelevantGroupIDs removes the "relevant_groups" edge to Group entities by IDs.
func (_u *PostUpdateOne) RemoveRelevantGroupIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveRelevantGroupIDs(ids...)
	return _u
}

// RemoveRelevantGroups removes "relevant_groups" edges to Group entities.
func (_u *PostUpdateOne) RemoveRelevantGroups(v ...*Group) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelevantGroupIDs(ids...)
}

// ClearFollowers clears all "followers" edges to the User entity.
func (_u *PostUpdateOne) ClearFollowers() *PostUpdateOne {
	_u.mutation.ClearFollowers()
	return _u
}

// RemoveFollowerIDs removes the "followers" edge to User entities by IDs.
func (_u *PostUpdateOne) RemoveFollowerIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveFollowerIDs(ids...)
	return _u
}

// RemoveFollowers removes "followers" edges to User entities.
func (_u *PostUpdateOne) RemoveFollowers(v ...*User) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFollowerIDs(ids...)
}

// ClearCoAuthorsArchive clears all "co_authors_archive" edges to the User entity.
func (_u *PostUpdateOne) ClearCoAuthorsArchive() *PostUpdateOne {
	_u.mutation.ClearCoAuthorsArchive()
	return _u
}

// RemoveCoAuthorsArchiveIDs removes the "co_authors_archive" edge to User entities by IDs.
func (_u *PostUpdateOne) RemoveCoAuthorsArchiveIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveCoAuthorsArchiveIDs(ids...)
	return _u
}

// RemoveCoAuthorsArchive removes "co_authors_archive" edges to User entities.
func (_u *PostUpdateOne) RemoveCoAuthorsArchive(v ...*User) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCoAuthorsArchiveIDs(ids...)
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.author"`)
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(post.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.InternalCode(); ok {
		_spec.SetField(post.FieldInternalCode, field.TypeString, value)
	}
	if _u.mutation.InternalCodeCleared() {
		_spec.ClearField(post.FieldInternalCode, field.TypeString)
	}
	if value, ok := _u.mutation.ManagementKey(); ok {
		_spec.SetField(post.FieldManagementKey, field.TypeString, value)
	}
	if _u.mutation.ManagementKeyCleared() {
		_spec.ClearField(post.FieldManagementKey, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(post.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ExtraData(); ok {
		_spec.SetField(post.FieldExtraData, field.TypeString, value)
	}
	if _u.mutation.ExtraDataCleared() {
		_spec.ClearField(post.FieldExtraData, field.TypeString)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoAuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsTable,
			Columns: []string{post.CoAuthorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCoAuthorsIDs(); len(nodes) > 0 && !_u.mutation.CoAuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsTable,
			Columns: []string{post.CoAuthorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoAuthorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsTable,
			Columns: []string{post.CoAuthorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelevantGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.RelevantGroupsTable,
			Columns: []string{post.RelevantGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelevantGroupsIDs(); len(nodes) > 0 && !_u.mutation.RelevantGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.RelevantGroupsTable,
			Columns: []string{post.RelevantGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelevantGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.RelevantGroupsTable,
			Columns: []string{post.RelevantGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.FollowersTable,
			Columns: []string{post.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFollowersIDs(); len(nodes) > 0 && !_u.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.FollowersTable,
			Columns: []string{post.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.FollowersTable,
			Columns: []string{post.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoAuthorsArchiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsArchiveTable,
			Columns: []string{post.CoAuthorsArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCoAuthorsArchiveIDs(); len(nodes) > 0 && !_u.mutation.CoAuthorsArchiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsArchiveTable,
			Columns: []string{post.CoAuthorsArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoAuthorsArchiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.CoAuthorsArchiveTable,
			Columns: []string{post.CoAuthorsArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
