// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/post"
	"github.com/Cromemadnd/lazyent/internal/tests/testenv/app/user/internal/data/ent/user"
	"github.com/google/uuid"
)

// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	// 数据库主键
	ID uuid.UUID `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// InternalCode holds the value of the "internal_code" field.
	InternalCode string `json:"internal_code,omitempty"`
	// ManagementKey holds the value of the "management_key" field.
	ManagementKey string `json:"-"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges        PostEdges `json:"edges"`
	user_posts   *uuid.UUID
	selectValues sql.SelectValues
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// Author holds the value of the author edge.
	Author *User `json:"author,omitempty"`
	// CoAuthors holds the value of the co_authors edge.
	CoAuthors []*User `json:"co_authors,omitempty"`
	// RelevantGroups holds the value of the relevant_groups edge.
	RelevantGroups []*Group `json:"relevant_groups,omitempty"`
	// Followers holds the value of the followers edge.
	Followers []*User `json:"followers,omitempty"`
	// CoAuthorsArchive holds the value of the co_authors_archive edge.
	CoAuthorsArchive []*User `json:"co_authors_archive,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) AuthorOrErr() (*User, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// CoAuthorsOrErr returns the CoAuthors value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) CoAuthorsOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.CoAuthors, nil
	}
	return nil, &NotLoadedError{edge: "co_authors"}
}

// RelevantGroupsOrErr returns the RelevantGroups value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) RelevantGroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[2] {
		return e.RelevantGroups, nil
	}
	return nil, &NotLoadedError{edge: "relevant_groups"}
}

// FollowersOrErr returns the Followers value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) FollowersOrErr() ([]*User, error) {
	if e.loadedTypes[3] {
		return e.Followers, nil
	}
	return nil, &NotLoadedError{edge: "followers"}
}

// CoAuthorsArchiveOrErr returns the CoAuthorsArchive value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) CoAuthorsArchiveOrErr() ([]*User, error) {
	if e.loadedTypes[4] {
		return e.CoAuthorsArchive, nil
	}
	return nil, &NotLoadedError{edge: "co_authors_archive"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Post) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case post.FieldTitle, post.FieldContent, post.FieldSlug, post.FieldInternalCode, post.FieldManagementKey, post.FieldSummary:
			values[i] = new(sql.NullString)
		case post.FieldCreatedAt, post.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case post.FieldID:
			values[i] = new(uuid.UUID)
		case post.ForeignKeys[0]: // user_posts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Post fields.
func (_m *Post) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case post.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case post.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case post.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case post.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case post.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case post.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case post.FieldInternalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_code", values[i])
			} else if value.Valid {
				_m.InternalCode = value.String
			}
		case post.FieldManagementKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field management_key", values[i])
			} else if value.Valid {
				_m.ManagementKey = value.String
			}
		case post.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case post.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_posts", values[i])
			} else if value.Valid {
				_m.user_posts = new(uuid.UUID)
				*_m.user_posts = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Post.
// This includes values selected through modifiers, order, etc.
func (_m *Post) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the Post entity.
func (_m *Post) QueryAuthor() *UserQuery {
	return NewPostClient(_m.config).QueryAuthor(_m)
}

// QueryCoAuthors queries the "co_authors" edge of the Post entity.
func (_m *Post) QueryCoAuthors() *UserQuery {
	return NewPostClient(_m.config).QueryCoAuthors(_m)
}

// QueryRelevantGroups queries the "relevant_groups" edge of the Post entity.
func (_m *Post) QueryRelevantGroups() *GroupQuery {
	return NewPostClient(_m.config).QueryRelevantGroups(_m)
}

// QueryFollowers queries the "followers" edge of the Post entity.
func (_m *Post) QueryFollowers() *UserQuery {
	return NewPostClient(_m.config).QueryFollowers(_m)
}

// QueryCoAuthorsArchive queries the "co_authors_archive" edge of the Post entity.
func (_m *Post) QueryCoAuthorsArchive() *UserQuery {
	return NewPostClient(_m.config).QueryCoAuthorsArchive(_m)
}

// Update returns a builder for updating this Post.
// Note that you need to call Post.Unwrap() before calling this method if this Post
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Post) Update() *PostUpdateOne {
	return NewPostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Post entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Post) Unwrap() *Post {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Post is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Post) String() string {
	var builder strings.Builder
	builder.WriteString("Post(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("internal_code=")
	builder.WriteString(_m.InternalCode)
	builder.WriteString(", ")
	builder.WriteString("management_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteByte(')')
	return builder.String()
}

// Posts is a parsable slice of Post.
type Posts []*Post
